# Generated by Django 5.2.10 on 2026-02-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_id_alter_category_id_alter_job_id'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE jobs_job ADD COLUMN IF NOT EXISTS requirements text NOT NULL DEFAULT '';",
            reverse_sql="ALTER TABLE jobs_job DROP COLUMN IF EXISTS requirements;"
        )
    ]
