# Generated by Django 5.2.10 on 2026-02-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_fix_missing_requirements'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE jobs_job ADD COLUMN IF NOT EXISTS currency varchar(10) NOT NULL DEFAULT 'USD';
                ALTER TABLE jobs_job ADD COLUMN IF NOT EXISTS salary_min integer NULL;
                ALTER TABLE jobs_job ADD COLUMN IF NOT EXISTS salary_max integer NULL;
            """,
            reverse_sql="""
                ALTER TABLE jobs_job DROP COLUMN IF EXISTS currency;
                ALTER TABLE jobs_job DROP COLUMN IF EXISTS salary_min;
                ALTER TABLE jobs_job DROP COLUMN IF EXISTS salary_max;
            """
        )
    ]
